### ISSUE TITLE
Unable to start the client running Gnome on Wayland (Fedora)

### ISSUE THREAD

**Issue by divinoro** [vfosterm/NordVPN-NetworkManager-Gui#18]
Trying your client, however I can't start it:

**FIrst**

```
./NordVPN/launch_nord
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/usr/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS32
Failed to load module: /usr/lib/gio/modules/libdconfsettings.so
Qt: Session management error: None of the authentication protocols specified are supported
Traceback (most recent call last):
  File "nord_nm_gui.py", line 416, in get_api_data
  File "site-packages/requests/api.py", line 75, in get
  File "site-packages/requests/api.py", line 60, in request
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 416, in send
  File "site-packages/requests/adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nord_nm_gui.py", line 1185, in <module>
  File "nord_nm_gui.py", line 37, in __init__
  File "nord_nm_gui.py", line 422, in get_api_data
AttributeError: 'MainWindow' object has no attribute 'statusbar'
[17211] Failed to execute script nord_nm_gui
[divinorum@div-laptop2 NordVPN-GUI]$ locate ca-certificates.crt
/usr/lib64/GNUstep/Libraries/gnustep-base/Versions/1.25/Resources/GSTLS/ca-certificates.crt
/var/lib/snapd/snap/core/8213/etc/ssl/certs/ca-certificates.crt
/var/lib/snapd/snap/core/8268/etc/ssl/certs/ca-certificates.crt
```

**Then**

```
QT_QPA_PLATFORM=wayland ./NordVPN/launch_nord
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

Any special dependency I'm missing here, please ? All qt5, qt5 python and qt5 wayland stuff seems to be installed.

Thanky you.

**Comment by vfosterm** [comment]
Have you tried installing the python dependencies and running just the python script?
This will probably be more compatible as with the compiled version all of the qt stuff is included in the package.
You can compile this afterwards yourself using 
`pyinstaller nord_nm_gui.py --icon nordvpnicon.png`

**Comment by divinoro** [comment]
Actually I have downloaded latest released version (1.5 alpha I think), error messages have changed, but still not running under Fedora Wayland. But now it seems like "normal" bug, not Wayland related:

```
$ python ./nord_nm_gui.py
QSocketNotifier: Can only be used with threads started with QThread

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:71:44: Invalid number for color value

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:72:44: Invalid number for color value

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:74:53: Invalid number for color value

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:75:53: Invalid number for color value

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:76:56: Invalid number for color value

(NordVPN:580752): Gtk-WARNING **: 14:53:03.541: Theme parsing error: colors.css:77:65: Invalid number for color value
Traceback (most recent call last):
  File "/usr/lib64/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'user_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./nord_nm_gui.py", line 1260, in <module>
    ui = MainWindow()
  File "./nord_nm_gui.py", line 47, in __init__
    self.login_ui()
  File "./nord_nm_gui.py", line 364, in login_ui
    self.check_configs()   # do configs exist else create
  File "./nord_nm_gui.py", line 392, in check_configs
    if self.config.get('USER', 'USER_NAME') != 'None':
  File "/usr/lib64/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'user_name' in section: 'USER'
```

I'll dig deeper into that anyway and will let you know what I have found. Thank you,

**Comment by vfosterm** [comment]
So far I have not gotten the alpha to work on GNOME, though I haven't had a chance to test it much.
The close to tray functionality does not work so you should probably fall back to the latest stable compatibility version.
https://github.com/vfosterm/NordVPN-NetworkManager-Gui/releases/download/v1.4.2/nord_vpn_v1-4-2_compatibility.tar.xz

**Comment by divinoro** [comment]
Well.. with this 1.4.2 version I'm running into the exactly same issues, as I described in my very first entry in this thread :-)

**Comment by alexaristotelous** [comment]
Yeap, having the same issue (Fedora 33). 

```
$ ./launch_nord 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "nord_nm_gui.py", line 385, in get_api_data
  File "requests/api.py", line 76, in get
  File "requests/api.py", line 61, in request
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 416, in send
  File "requests/adapters.py", line 227, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nord_nm_gui.py", line 1154, in <module>
  File "nord_nm_gui.py", line 37, in __init__
  File "nord_nm_gui.py", line 391, in get_api_data
AttributeError: 'MainWindow' object has no attribute 'statusbar'
[8534] Failed to execute script nord_nm_gui
```

**Comment by ahallrq** [comment]
@divinoro @alexaristotelous In order to run this on Fedora I had to `ln -s /etc/pki/tls/certs/{ca-bundle.crt,ca-certificates.crt}`. Doing so makes `ca-certificates.crt` show up in `/etc/ssl/certs/` (which in turn is just a symlink to another folder anyway)
Certs appear to be in [different locations on different distros](https://serverfault.com/a/722646).
